#jdbc:postgresql://localhost:5432/camunda
spring.datasource:
  url: jdbc:postgresql://localhost:5432/camunda
  username: postgres
  password: postgres
  driver-class-name : org.postgresql.Driver
#spring.h2.console.enabled: true
camunda.bpm.database.type: postgres


spring:
  jersey:
    application-path: engine-rest


logging:
  level:
    root: INFO
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: vignesh
  history-level: audit
  authorization:
    enabled: true
  #filter:
    #create: All tasks

server:
  port: 9092
  servlet.context-path: /camunda

keycloak:
  enabled: true
  ssl-required : external
  bearer-only : true
  auth-server-url : https://localhost:9001/auth
  realm : orbeonRealm
  resource : camundaApi
  public-client : true
  principal-attribute : subject
  use-resource-role-mappings : true
  securityConstraints:
    - authRoles: [camunda-rest-api-admin-crole]
      securityCollections:
        - name: API Private Data
          patterns: ['/camunda/engine-rest/*','/engine-rest/*']